name: Mineral

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  fishing:
    runs-on: ubuntu-latest
    concurrency:
      group: mineral

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'LalatinaHub/Mineral'
      - name: Get secrets
        run: |
          echo ${{ secrets.BOT_TOKEN }} > ./session
          echo ${{ secrets.API_ID }} > ./api_id
          echo ${{ secrets.API_HASH }} > ./api_hash
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Start Mineral
        run: |
          npm install && npx tsc && node ./app/index.js
      - name: Push file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'result/'
          destination_repo: 'LalatinaHub/Mineral'
          user_email: 'santrialanwari@gmail.com'
          user_name: 'Dicky Mulia Fiqri'
          commit_message: 'Update Nodes'
